export interface Character {
  id: string
  name: string
  source: string
  category: Category
  mbti: string
  enneagram: string
  description: string
}

export type Category = 'Movies' | 'TV Shows' | 'Books' | 'Music' | 'Business'

export const CHARACTERS: Character[] = [
  // ── Movies ─────────────────────────────────────────────────────────────────
  {
    id: 'darth-vader',
    name: 'Darth Vader',
    source: 'Star Wars',
    category: 'Movies',
    mbti: 'INTJ',
    enneagram: '8w9',
    description: 'A domineering strategist driven by control and a suppressed vulnerability beneath his iron will.',
  },
  {
    id: 'tony-stark',
    name: 'Tony Stark',
    source: 'Iron Man / MCU',
    category: 'Movies',
    mbti: 'ENTP',
    enneagram: '7w8',
    description: 'A brilliantly chaotic innovator who uses wit and invention to outrun his own fear of inadequacy.',
  },
  {
    id: 'hermione-granger',
    name: 'Hermione Granger',
    source: 'Harry Potter',
    category: 'Movies',
    mbti: 'ISTJ',
    enneagram: '1w2',
    description: 'A meticulous rule-follower whose deep moral sense drives her to do what is right, not what is easy.',
  },
  {
    id: 'the-joker',
    name: 'The Joker',
    source: 'The Dark Knight',
    category: 'Movies',
    mbti: 'ENTP',
    enneagram: '7w8',
    description: 'A chaos-agent who uses dark humor and provocation to expose the fragility of social order.',
  },
  {
    id: 'forrest-gump',
    name: 'Forrest Gump',
    source: 'Forrest Gump',
    category: 'Movies',
    mbti: 'ISFJ',
    enneagram: '9w1',
    description: 'A gentle, loyal soul who moves through life with uncommon grace by simply following his heart.',
  },
  {
    id: 'vito-corleone',
    name: 'Vito Corleone',
    source: 'The Godfather',
    category: 'Movies',
    mbti: 'INTJ',
    enneagram: '8w9',
    description: 'A quietly powerful patriarch who wields authority through respect, patience, and calculated restraint.',
  },
  {
    id: 'hannibal-lecter',
    name: 'Hannibal Lecter',
    source: 'Silence of the Lambs',
    category: 'Movies',
    mbti: 'INTJ',
    enneagram: '5w4',
    description: 'A supremely intelligent aesthete who views people as either intellectual companions or beneath consideration.',
  },
  {
    id: 'ellen-ripley',
    name: 'Ellen Ripley',
    source: 'Alien',
    category: 'Movies',
    mbti: 'ISTJ',
    enneagram: '6w5',
    description: 'A pragmatic survivor whose fierce protectiveness and procedural thinking keep her alive against all odds.',
  },
  {
    id: 'captain-jack-sparrow',
    name: 'Jack Sparrow',
    source: 'Pirates of the Caribbean',
    category: 'Movies',
    mbti: 'ENTP',
    enneagram: '7w6',
    description: 'A charming opportunist who masks sharp instincts behind an elaborate facade of bumbling unpredictability.',
  },
  {
    id: 'tyler-durden',
    name: 'Tyler Durden',
    source: 'Fight Club',
    category: 'Movies',
    mbti: 'ESTP',
    enneagram: '8w7',
    description: 'A nihilistic provocateur who tears down comfort to force others into confronting their authentic selves.',
  },
  {
    id: 'andy-dufresne',
    name: 'Andy Dufresne',
    source: 'The Shawshank Redemption',
    category: 'Movies',
    mbti: 'INTJ',
    enneagram: '5w4',
    description: 'A quietly determined strategist who endures injustice with dignity while never surrendering his inner world.',
  },
  {
    id: 'indiana-jones',
    name: 'Indiana Jones',
    source: 'Indiana Jones',
    category: 'Movies',
    mbti: 'ISTP',
    enneagram: '7w8',
    description: 'An adventurous pragmatist who thrives under pressure and finds more meaning in the chase than the prize.',
  },
  // ── TV Shows ───────────────────────────────────────────────────────────────
  {
    id: 'walter-white',
    name: 'Walter White',
    source: 'Breaking Bad',
    category: 'TV Shows',
    mbti: 'INTJ',
    enneagram: '3w4',
    description: 'A pride-wounded achiever who dismantles his own identity while building the empire his ego demands.',
  },
  {
    id: 'michael-scott',
    name: 'Michael Scott',
    source: 'The Office',
    category: 'TV Shows',
    mbti: 'ENFP',
    enneagram: '7w6',
    description: 'An enthusiastic people-pleaser whose desperate need for connection both sabotages and defines his leadership.',
  },
  {
    id: 'sheldon-cooper',
    name: 'Sheldon Cooper',
    source: 'The Big Bang Theory',
    category: 'TV Shows',
    mbti: 'ISTJ',
    enneagram: '5w6',
    description: 'A hyper-rational systems-thinker who retreats into knowledge to manage a world that feels emotionally chaotic.',
  },
  {
    id: 'cersei-lannister',
    name: 'Cersei Lannister',
    source: 'Game of Thrones',
    category: 'TV Shows',
    mbti: 'ENTJ',
    enneagram: '3w2',
    description: 'A ruthlessly image-conscious strategist who pursues power to compensate for the vulnerability she never shows.',
  },
  {
    id: 'ted-lasso',
    name: 'Ted Lasso',
    source: 'Ted Lasso',
    category: 'TV Shows',
    mbti: 'ENFJ',
    enneagram: '2w3',
    description: 'An infectiously optimistic coach whose radical belief in people heals them in ways tactics never could.',
  },
  {
    id: 'don-draper',
    name: 'Don Draper',
    source: 'Mad Men',
    category: 'TV Shows',
    mbti: 'INTJ',
    enneagram: '3w4',
    description: 'A self-constructed persona built on genius and reinvention, haunted by the identity he buried underneath.',
  },
  {
    id: 'tyrion-lannister',
    name: 'Tyrion Lannister',
    source: 'Game of Thrones',
    category: 'TV Shows',
    mbti: 'ENTP',
    enneagram: '7w6',
    description: 'A sharp-minded political survivor who uses wit and wine as armor against a world that has always underestimated him.',
  },
  {
    id: 'daenerys-targaryen',
    name: 'Daenerys Targaryen',
    source: 'Game of Thrones',
    category: 'TV Shows',
    mbti: 'INFJ',
    enneagram: '8w9',
    description: 'A visionary crusader whose moral certainty and hunger for justice curdles into terrifying rigidity when she feels betrayed.',
  },
  {
    id: 'tony-soprano',
    name: 'Tony Soprano',
    source: 'The Sopranos',
    category: 'TV Shows',
    mbti: 'ESTP',
    enneagram: '8w7',
    description: 'A volatile patriarch who oscillates between ruthless dominance and a buried tenderness he can never fully admit to.',
  },
  {
    id: 'carrie-bradshaw',
    name: 'Carrie Bradshaw',
    source: 'Sex and the City',
    category: 'TV Shows',
    mbti: 'ENFP',
    enneagram: '4w3',
    description: 'A romantic individualist who processes her inner life through storytelling and never stops searching for her defining love.',
  },
  {
    id: 'leslie-knope',
    name: 'Leslie Knope',
    source: 'Parks & Recreation',
    category: 'TV Shows',
    mbti: 'ENFJ',
    enneagram: '3w2',
    description: 'A relentlessly driven public servant whose ambition is fueled entirely by genuine love for her community.',
  },
  // ── Books ──────────────────────────────────────────────────────────────────
  {
    id: 'sherlock-holmes',
    name: 'Sherlock Holmes',
    source: 'Sherlock Holmes (Doyle)',
    category: 'Books',
    mbti: 'INTP',
    enneagram: '5w6',
    description: 'A relentless analyst who treats human beings as data sets and boredom as his most dangerous enemy.',
  },
  {
    id: 'elizabeth-bennet',
    name: 'Elizabeth Bennet',
    source: 'Pride and Prejudice',
    category: 'Books',
    mbti: 'ENTJ',
    enneagram: '1w2',
    description: "A quick-witted moralist who must learn that her own pride and judgment can blind her as thoroughly as others' prejudice.",
  },
  {
    id: 'jay-gatsby',
    name: 'Jay Gatsby',
    source: 'The Great Gatsby',
    category: 'Books',
    mbti: 'ENFJ',
    enneagram: '3w2',
    description: 'A charismatic self-mythologist who pursues an idealized past with a devotion that dissolves the present entirely.',
  },
  {
    id: 'atticus-finch',
    name: 'Atticus Finch',
    source: 'To Kill a Mockingbird',
    category: 'Books',
    mbti: 'INFJ',
    enneagram: '1w9',
    description: 'A principled idealist who models quiet moral courage as the only dignified response to a broken world.',
  },
  {
    id: 'holden-caulfield',
    name: 'Holden Caulfield',
    source: 'The Catcher in the Rye',
    category: 'Books',
    mbti: 'INFP',
    enneagram: '4w5',
    description: 'A sensitive misfit whose disdain for phoniness masks a desperate longing to protect innocence — including his own.',
  },
  {
    id: 'raskolnikov',
    name: 'Raskolnikov',
    source: 'Crime and Punishment',
    category: 'Books',
    mbti: 'INTJ',
    enneagram: '4w3',
    description: 'A proud intellectual who attempts to transcend conventional morality and discovers the self cannot be philosophized away.',
  },
  {
    id: 'emma-woodhouse',
    name: 'Emma Woodhouse',
    source: 'Emma (Austen)',
    category: 'Books',
    mbti: 'ENTJ',
    enneagram: '3w4',
    description: 'A charming overconfident matchmaker whose growth arc is learning that cleverness without humility is merely interference.',
  },
  {
    id: 'frodo-baggins',
    name: 'Frodo Baggins',
    source: 'Lord of the Rings',
    category: 'Books',
    mbti: 'INFP',
    enneagram: '9w1',
    description: 'An unassuming idealist whose endurance is not heroic bravado but a quiet, stubborn refusal to surrender what matters.',
  },
  {
    id: 'winston-smith',
    name: 'Winston Smith',
    source: '1984 (Orwell)',
    category: 'Books',
    mbti: 'INFP',
    enneagram: '6w5',
    description: 'A quietly rebellious truth-seeker who clings to individual memory as the last territory the state cannot colonize.',
  },
  // ── Music ──────────────────────────────────────────────────────────────────
  {
    id: 'taylor-swift',
    name: 'Taylor Swift',
    source: 'Singer-Songwriter',
    category: 'Music',
    mbti: 'ESFJ',
    enneagram: '3w2',
    description: 'A meticulous image-builder who converts personal heartbreak into universally resonant anthems with surgical precision.',
  },
  {
    id: 'kanye-west',
    name: 'Kanye West',
    source: 'Rapper / Producer',
    category: 'Music',
    mbti: 'ENFP',
    enneagram: '4w3',
    description: 'A fiercely original provocateur whose genius and grandiosity are two expressions of the same hunger to be seen fully.',
  },
  {
    id: 'beyonce',
    name: 'Beyoncé',
    source: 'Singer / Performer',
    category: 'Music',
    mbti: 'ESTJ',
    enneagram: '3w2',
    description: 'A disciplined perfectionist who channels relentless preparation into performances that feel effortlessly transcendent.',
  },
  {
    id: 'david-bowie',
    name: 'David Bowie',
    source: 'Singer-Songwriter',
    category: 'Music',
    mbti: 'ENTP',
    enneagram: '4w3',
    description: 'A restless shape-shifter who treated personal reinvention as both artistic practice and existential survival strategy.',
  },
  {
    id: 'billie-eilish',
    name: 'Billie Eilish',
    source: 'Singer-Songwriter',
    category: 'Music',
    mbti: 'ISFP',
    enneagram: '4w5',
    description: 'An acutely sensitive artist who transforms private melancholy into an aesthetic that feels simultaneously confessional and universal.',
  },
  {
    id: 'freddie-mercury',
    name: 'Freddie Mercury',
    source: 'Queen',
    category: 'Music',
    mbti: 'ENFP',
    enneagram: '7w8',
    description: 'A flamboyant maximalist whose showmanship concealed a private, deeply feeling person in perpetual pursuit of beauty.',
  },
  {
    id: 'bob-dylan',
    name: 'Bob Dylan',
    source: 'Singer-Songwriter',
    category: 'Music',
    mbti: 'INFP',
    enneagram: '5w4',
    description: 'An elusive, internally driven poet who guards his inner world fiercely while exposing it completely through his art.',
  },
  {
    id: 'kurt-cobain',
    name: 'Kurt Cobain',
    source: 'Nirvana',
    category: 'Music',
    mbti: 'ISFP',
    enneagram: '4w5',
    description: 'A raw, hypersensitive artist whose self-contradiction — craving fame while despising its cost — defined his tragic arc.',
  },
  // ── Business ───────────────────────────────────────────────────────────────
  {
    id: 'elon-musk',
    name: 'Elon Musk',
    source: 'Tesla / SpaceX',
    category: 'Business',
    mbti: 'INTJ',
    enneagram: '5w6',
    description: 'A systems-obsessed first-principles thinker who imposes his vision on industries with a singular disregard for conventional limits.',
  },
  {
    id: 'steve-jobs',
    name: 'Steve Jobs',
    source: 'Apple',
    category: 'Business',
    mbti: 'ENTJ',
    enneagram: '4w3',
    description: 'A demanding perfectionist who fused artistic sensibility with commercial vision, treating personal taste as a universal mandate.',
  },
  {
    id: 'oprah-winfrey',
    name: 'Oprah Winfrey',
    source: 'Media / Philanthropy',
    category: 'Business',
    mbti: 'ENFJ',
    enneagram: '2w3',
    description: 'An empathic connector who built a media empire by turning authentic vulnerability into a platform for human transformation.',
  },
  {
    id: 'jeff-bezos',
    name: 'Jeff Bezos',
    source: 'Amazon',
    category: 'Business',
    mbti: 'INTJ',
    enneagram: '3w4',
    description: 'A long-horizon strategist who treats obsessive customer focus as both a moral principle and a competitive weapon.',
  },
  {
    id: 'warren-buffett',
    name: 'Warren Buffett',
    source: 'Berkshire Hathaway',
    category: 'Business',
    mbti: 'ISTJ',
    enneagram: '5w6',
    description: 'A patient, methodical value-seeker whose quiet lifestyle and voracious reading habits are the actual source of his edge.',
  },
  {
    id: 'sheryl-sandberg',
    name: 'Sheryl Sandberg',
    source: 'Meta / Lean In',
    category: 'Business',
    mbti: 'ENTJ',
    enneagram: '3w2',
    description: 'A driven executer who pairs high achievement with genuine advocacy, using her platform to push others forward alongside herself.',
  },
  {
    id: 'bill-gates',
    name: 'Bill Gates',
    source: 'Microsoft / Gates Foundation',
    category: 'Business',
    mbti: 'INTP',
    enneagram: '5w6',
    description: 'A compulsive systems-thinker who applied the same obsessive rigor to software, wealth, and global health with equal intensity.',
  },
  {
    id: 'sara-blakely',
    name: 'Sara Blakely',
    source: 'Spanx',
    category: 'Business',
    mbti: 'ENFP',
    enneagram: '7w8',
    description: 'An optimistic entrepreneur who turned a simple insight and relentless self-belief into a billion-dollar brand from scratch.',
  },
]
