import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service — Innermind',
  description: 'The terms and conditions governing your use of the Innermind platform.',
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      {/* Hero */}
      <div className="mb-12">
        <p className="mb-3 text-xs font-semibold uppercase tracking-widest text-amber-500">Legal</p>
        <h1 className="font-serif text-4xl text-stone-100">Terms of Service</h1>
        <p className="mt-4 text-stone-400">
          Effective date: March 1, 2026. Last updated: March 1, 2026.
        </p>
      </div>

      <div className="space-y-10 text-stone-400">

        {/* Acceptance */}
        <section>
          <h2 className="mb-4 font-serif text-2xl text-stone-200">1. Acceptance of terms</h2>
          <p className="leading-relaxed">
            By accessing or using Innermind (&ldquo;the Service&rdquo;), you agree to be bound by these
            Terms of Service (&ldquo;Terms&rdquo;). Please read them carefully. If you do not agree to
            these Terms, you may not use the Service. These Terms apply to all visitors, users,
            and anyone who accesses or uses the Service.
          </p>
          <p className="mt-4 leading-relaxed">
            These Terms constitute a legally binding agreement between you and Innermind, Inc.
            (&ldquo;Innermind&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;), a company incorporated under the laws of California.
          </p>
        </section>

        {/* Service description */}
        <section>
          <h2 className="mb-4 font-serif text-2xl text-stone-200">2. Service description</h2>
          <p className="leading-relaxed">
            Innermind is a psychological profiling and self-understanding platform. The Service
            provides access to science-backed psychological assessments (including Big Five
            personality, values inventories, attachment style, Enneagram, and others), AI-powered
            profile synthesis, personalised insights, a reflection journal, an AI coaching
            interface, and team compatibility tools.
          </p>
          <p className="mt-4 leading-relaxed">
            Innermind is a tool for self-reflection and personal growth. It is <strong className="text-stone-300">not</strong> a
            licensed mental health service, clinical diagnostic tool, therapy service, or
            medical device. Profiles and insights generated by Innermind are intended for
            informational and self-reflective purposes only. See Section 9 for our AI disclaimer.
          </p>
        </section>

        {/* Account registration */}
        <section>
          <h2 className="mb-4 font-serif text-2xl text-stone-200">3. Account registration</h2>
          <p className="mb-3 leading-relaxed">
            To use the Service, you must create an account by providing a valid email address.
            We use magic link authentication — a one-time login link is sent to your email each
            time you sign in. You are responsible for keeping access to your email account secure.
          </p>
          <ul className="space-y-2 text-sm leading-relaxed">
            <li className="flex items-start gap-3">
              <span className="mt-0.5 shrink-0 text-amber-500">✦</span>
              You must be at least 18 years of age to create an account.
            </li>
            <li className="flex items-start gap-3">
              <span className="mt-0.5 shrink-0 text-amber-500">✦</span>
              You must provide accurate and complete information during registration.
            </li>
            <li className="flex items-start gap-3">
              <span className="mt-0.5 shrink-0 text-amber-500">✦</span>
              You are responsible for all activity that occurs under your account.
            </li>
            <li className="flex items-start gap-3">
              <span className="mt-0.5 shrink-0 text-amber-500">✦</span>
              You must notify us immediately at{' '}
              <a href="mailto:privacy@innermind.app" className="text-amber-400 underline hover:text-amber-300">
                privacy@innermind.app
              </a>{' '}
              if you suspect unauthorised access to your account.
            </li>
          </ul>
        </section>

        {/* Subscription tiers */}
        <section>
          <h2 className="mb-4 font-serif text-2xl text-stone-200">4. Subscription tiers and billing</h2>
          <p className="mb-5 leading-relaxed">
            Innermind offers the following subscription plans:
          </p>
          <div className="space-y-4">
            {[
              {
                name: 'Free',
                price: '$0 / month',
                description:
                  'Access to core assessments, basic profile generation, and limited insights. No credit card required.',
              },
              {
                name: 'Pro',
                price: '$12 / month',
                description:
                  'Full access to all assessment frameworks, AI coach, unlimited journal, growth recommendations, PDF export, and profile sharing.',
              },
              {
                name: 'Teams',
                price: '$49 / month',
                description:
                  'Everything in Pro, plus a team workspace to share profiles, view compatibility maps, and collaborate with up to 20 members.',
              },
            ].map((tier) => (
              <div key={tier.name} className="rounded-2xl border border-stone-800 bg-stone-900/50 p-5">
                <div className="mb-1 flex items-center justify-between">
                  <h3 className="font-semibold text-stone-200">{tier.name}</h3>
                  <span className="text-sm font-medium text-amber-400">{tier.price}</span>
                </div>
                <p className="text-sm leading-relaxed">{tier.description}</p>
              </div>
            ))}
          </div>
          <p className="mt-5 text-sm leading-relaxed">
            Subscriptions are billed monthly and renew automatically. You may cancel at any time
            from your account settings. Cancellation takes effect at the end of the current billing
            period. We do not offer pro-rated refunds for partial months. Pricing is subject to
            change with 30 days&apos; notice to active subscribers.
          </p>
        </section>

        {/* Acceptable use */}
        <section>
          <h2 className="mb-4 font-serif text-2xl text-stone-200">5. Acceptable use</h2>
          <p className="mb-4 leading-relaxed">
            You agree to use the Service only for lawful purposes and in accordance with these
            Terms. You agree <strong className="text-stone-300">not</strong> to:
          </p>
          <ul className="space-y-2 text-sm leading-relaxed">
            {[
              'Use the Service if you are under 18 years of age.',
              'Scrape, crawl, or systematically extract data from the Service using automated tools.',
              'Reverse-engineer, decompile, or attempt to extract source code from the platform.',
              'Attempt to gain unauthorised access to any part of the Service or any other user\'s account or data.',
              'Use the Service to harass, harm, or deceive others.',
              'Impersonate any person or entity, or misrepresent your affiliation with any person or entity.',
              'Use the Service for any commercial purpose other than as expressly permitted by Innermind.',
              'Upload or transmit malicious code, viruses, or any software intended to damage or disrupt the Service.',
              'Circumvent, disable, or otherwise interfere with security-related features of the Service.',
              'Share your profile or account access for the purpose of circumventing subscription limits.',
            ].map((rule) => (
              <li key={rule} className="flex items-start gap-3">
                <span className="mt-0.5 shrink-0 text-rose-500">✕</span>
                {rule}
              </li>
            ))}
          </ul>
          <p className="mt-4 text-sm leading-relaxed">
            Violation of these rules may result in suspension or permanent termination of your
            account. We reserve the right to report illegal activity to appropriate authorities.
          </p>
        </section>

        {/* AI disclaimer */}
        <section>
          <h2 className="mb-4 font-serif text-2xl text-stone-200">6. AI-generated content disclaimer</h2>
          <div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-6">
            <p className="mb-3 text-sm font-medium text-stone-200">Important notice about AI-generated profiles and insights</p>
            <p className="text-sm leading-relaxed">
              Psychological profiles, insights, growth recommendations, and AI coach responses
              generated by Innermind are produced using large language model AI (Anthropic&apos;s Claude).
              These outputs are designed to support self-reflection and personal growth.
            </p>
            <p className="mt-3 text-sm leading-relaxed">
              They are <strong className="text-stone-300">not</strong> a substitute for professional mental health
              care, clinical diagnosis, psychotherapy, or medical advice. Innermind profiles do not
              constitute a clinical assessment and should not be used as the basis for clinical,
              employment, legal, or other consequential decisions about yourself or others.
            </p>
            <p className="mt-3 text-sm leading-relaxed">
              AI outputs may contain errors or reflect the limitations of the underlying model.
              If you are experiencing a mental health crisis, please contact a licensed mental health
              professional or your local emergency services.
            </p>
          </div>
        </section>

        {/* Intellectual property */}
        <section>
          <h2 className="mb-4 font-serif text-2xl text-stone-200">7. Intellectual property</h2>
          <p className="mb-3 leading-relaxed">
            <strong className="text-stone-300">Platform:</strong> Innermind, Inc. owns all rights,
            title, and interest in and to the Innermind platform, including its software, design,
            branding, assessment instruments, and all content created or provided by Innermind.
            You may not copy, reproduce, distribute, or create derivative works of the platform
            without our express written permission.
          </p>
          <p className="leading-relaxed">
            <strong className="text-stone-300">Your data:</strong> You own all data you create
            within Innermind — your assessment responses, journal entries, and reflections. By using
            the Service, you grant Innermind a limited, non-exclusive licence to process your data
            for the sole purpose of providing the Service to you. We do not claim ownership of your
            personal data and will not use it for any purpose other than delivering the Service.
          </p>
        </section>

        {/* Termination */}
        <section>
          <h2 className="mb-4 font-serif text-2xl text-stone-200">8. Termination</h2>
          <p className="mb-3 leading-relaxed">
            You may delete your account at any time from your account settings. Upon deletion,
            all your data will be permanently removed within 30 days as described in our
            Privacy Policy.
          </p>
          <p className="leading-relaxed">
            Innermind may suspend or terminate your account, with or without notice, if we
            determine that you have violated these Terms, engaged in abusive or fraudulent
            activity, or if required by law. In cases of suspected illegal activity, we may
            preserve data as required by law enforcement. Termination of your account does
            not entitle you to a refund of any prepaid subscription fees.
          </p>
        </section>

        {/* Limitation of liability */}
        <section>
          <h2 className="mb-4 font-serif text-2xl text-stone-200">9. Limitation of liability</h2>
          <p className="mb-3 text-sm leading-relaxed">
            To the maximum extent permitted by applicable law, Innermind, Inc. and its officers,
            directors, employees, and agents shall not be liable for any indirect, incidental,
            special, consequential, or punitive damages arising from your use of or inability to
            use the Service, including but not limited to loss of data, loss of profits, or
            emotional distress.
          </p>
          <p className="text-sm leading-relaxed">
            Our total liability to you for any claim arising from these Terms or the Service
            shall not exceed the amount you paid us in the 12 months preceding the claim.
            The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind,
            either express or implied.
          </p>
        </section>

        {/* Governing law */}
        <section>
          <h2 className="mb-4 font-serif text-2xl text-stone-200">10. Governing law</h2>
          <p className="leading-relaxed">
            These Terms shall be governed by and construed in accordance with the laws of the
            State of California, United States, without regard to its conflict of law provisions.
            Any dispute arising from these Terms shall be resolved exclusively in the state or
            federal courts located in San Francisco County, California. If you are located in
            the European Union, mandatory consumer protection laws of your country of residence
            may also apply.
          </p>
        </section>

        {/* Changes */}
        <section>
          <h2 className="mb-4 font-serif text-2xl text-stone-200">11. Changes to these terms</h2>
          <p className="leading-relaxed">
            We may update these Terms from time to time. Material changes will be communicated
            by email or in-app notice at least 14 days before they take effect. Your continued
            use of the Service after changes become effective constitutes your acceptance of the
            revised Terms.
          </p>
        </section>

        {/* Contact */}
        <section className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-6">
          <h2 className="mb-3 font-serif text-xl text-stone-200">Questions about these terms</h2>
          <p className="mb-2 text-sm leading-relaxed">
            If you have any questions about these Terms of Service, please contact us:
          </p>
          <p className="text-sm">
            <strong className="text-stone-300">Email:</strong>{' '}
            <a href="mailto:privacy@innermind.app" className="text-amber-400 underline hover:text-amber-300">
              privacy@innermind.app
            </a>
          </p>
          <p className="mt-1 text-sm">
            <strong className="text-stone-300">Company:</strong> Innermind, Inc., California, USA
          </p>
          <p className="mt-4 text-sm text-stone-500">
            Also see our{' '}
            <Link href="/privacy" className="text-amber-400 underline hover:text-amber-300">
              Privacy Policy
            </Link>
            .
          </p>
        </section>

      </div>
    </div>
  )
}
